---
swagger: '2.0'
info:
  title: Authenticator
  version: 0.0.1
x-package-name: com.github.slamdev.micro.playground.services.authenticator.api
x-api-name-prefix: Authenticator
x-path-variable-name: services.authenticator.url
basePath: /api
paths:
  /token:
    post:
      operationId: generateToken
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: credential
          in: body
          schema:
            $ref: '#/definitions/CredentialDto'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/TokenDto'
      x-security-role: ROLE_ANONYMOUS
  /user:
    put:
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: credential
          in: body
          schema:
            $ref: '#/definitions/CredentialDto'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/UserDto'
      x-security-role: ROLE_ADMIN
definitions:
  CredentialDto:
    type: object
    properties:
      email:
        type: string
        format: email
      password:
        type: string
  UserDto:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
        format: email
      role:
        type: string
        enum:
          - ANONYMOUS
          - USER
          - ADMIN
  TokenDto:
    type: object
    properties:
      token:
        type: string
