version: '2.1' # do not migrate to 3.x version because of https://github.com/docker/compose/issues/4305
services:
  postfix-relay:
    image: alterrebe/postfix-relay
    environment:
      SMTP_LOGIN: apikey
      SMTP_PASSWORD: ${MT_SMTP_PASSWORD}
      EXT_RELAY_HOST: smtp.sendgrid.net
    expose:
      - 25
networks:
  default:
    external:
      name: micro-playground
