version: '2.1' # do not migrate to 3.x version because of https://github.com/docker/compose/issues/4305
services:
  mongo:
    image: mongo
    volumes:
      - ./build/mongo:/data/db
#    healthcheck:
#      test: ['CMD-SHELL', 'echo "db.stats().ok" | mongo --quiet || exit1']
#      interval: 5s
#      timeout: 3s
#      retries: 5
  elasticsearch:
    image: elasticsearch:2-alpine
    command: ['elasticsearch', '-Des.cluster.name=graylog']
    volumes:
      - ./build/elasticsearch:/usr/share/elasticsearch/data
#    healthcheck:
#      test: ['CMD-SHELL', 'wget -q "http://127.0.0.1:9200" -O /dev/null']
#      interval: 5s
#      timeout: 3s
#      retries: 5
  graylog:
    build:
      context: .
    image: graylog2/server:2.2.1-1
    volumes:
      - ./build/graylog/journal:/usr/share/graylog/data/journal
    environment:
      GRAYLOG_PASSWORD_SECRET: 8bd4dee15dasDq32
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 # admin
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api/
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "smtp"
      GRAYLOG_TRANSPORT_EMAIL_PORT: 25
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 12201/udp:12201/udp
      - 1514/udp:1514/udp
